export enum Attribute {
    None, /** 占位符 no usages */
    CollectEfficiency,
    CollectEfficiencyPct,
    CollectDuration,
    CollectDurationPct,
    WoodCollectEfficiency,
    WoodCollectEfficiencyPct,
    WaterCollectEfficiency,
    WaterCollectEfficiencyPct,
    RockCollectEfficiency,
    RockCollectEfficiencyPct,
    SeedCollectEfficiency,
    SeedCollectEfficiencyPct,
    WoodCollectDuration,
    WoodCollectDurationPct,
    WaterCollectDuration,
    WaterCollectDurationPct,
    RockCollectDuration,
    RockCollectDurationPct,
    SeedCollectDuration,
    SeedCollectDurationPct,
    ALLConscriptNumMax,
    DefenseAttackVal,
    DefenseAttackPct,
    DefenseHPMax,
    DefenseHPMaxPct,
    ConstructDuration,
    ConstructDurationReduce,
    ConstructDurationReducePct,
    ProduceDuration,
    ProduceDurationReduce,
    ProduceDurationReducePct,
}
export enum BattleAttribute {
    None,
    HPMax,
    HPMaxPct,
    HPCur,
    AttackVal,
    AttackPct,
    AttackSpeed,
    AttackSpeedPct,
    StaminaPct,
    GroundMoveSpeed,
    GroundMoveSpeedPct,
    SkillCD,
    SkillCDPct,
    CriticalPct,
    CriticalIncrPct,
    CriticalDmgPct,
    EvadeProb,
    ShieldCoverMax,
    ShieldCoverCur,
    HitResumeVal,
    KillResumeVal,
    DamageReduce,
    DamageIncrease,
    Vampire,

}

export const ProductionAttributes: { [AttributeId: number]: { AttrName: string, isPercent: boolean } } = {
    [Attribute.CollectEfficiency]: { AttrName: '采集效率', isPercent: true },
    [Attribute.CollectEfficiencyPct]: { AttrName: '采集效率百分比', isPercent: true },
    [Attribute.CollectDuration]: { AttrName: '可采集时长', isPercent: false },
    [Attribute.CollectDurationPct]: { AttrName: '可采集时长百分比', isPercent: true },
    [Attribute.WoodCollectEfficiency]: { AttrName: '原木采集效率', isPercent: true },
    [Attribute.WoodCollectEfficiencyPct]: { AttrName: '原木采集效率百分比', isPercent: true },
    [Attribute.WaterCollectEfficiency]: { AttrName: '纯水采集效率', isPercent: true },
    [Attribute.WaterCollectEfficiencyPct]: { AttrName: '纯水采集效率百分比', isPercent: true },
    [Attribute.RockCollectEfficiency]: { AttrName: '顽石采集效率', isPercent: true },
    [Attribute.RockCollectEfficiencyPct]: { AttrName: '顽石采集效率百分比', isPercent: true },
    [Attribute.SeedCollectEfficiency]: { AttrName: '种子采集效率', isPercent: true },
    [Attribute.SeedCollectEfficiencyPct]: { AttrName: '种子采集效率百分比', isPercent: true },
    [Attribute.WoodCollectDuration]: { AttrName: '原木可采集时长', isPercent: true },
    [Attribute.WoodCollectDurationPct]: { AttrName: '原木可采集时长百分比', isPercent: true },
    [Attribute.WaterCollectDuration]: { AttrName: '纯水可采集时长', isPercent: true },
    [Attribute.WaterCollectDurationPct]: { AttrName: '纯水可采集时长百分比', isPercent: true },
    [Attribute.RockCollectDuration]: { AttrName: '顽石可采集时长', isPercent: true },
    [Attribute.RockCollectDurationPct]: { AttrName: '顽石可采集时长百分比', isPercent: true },
    [Attribute.SeedCollectDuration]: { AttrName: '种子可采集时长', isPercent: true },
    [Attribute.SeedCollectDurationPct]: { AttrName: '种子可采集时长百分比', isPercent: true },
    [Attribute.ALLConscriptNumMax]: { AttrName: '所有兵种征兵最大数量', isPercent: false },
    [Attribute.DefenseAttackVal]: { AttrName: '驻守角色攻击值', isPercent: false },
    [Attribute.DefenseAttackPct]: { AttrName: '驻守角色攻击百分比', isPercent: true },
    [Attribute.DefenseHPMax]: { AttrName: '驻守角色生命值', isPercent: false },
    [Attribute.DefenseHPMaxPct]: { AttrName: '驻守角色生命百分比', isPercent: true },
    [Attribute.ConstructDuration]: { AttrName: '建造时间值', isPercent: false },
    [Attribute.ConstructDurationReduce]: { AttrName: '建造时间减少值', isPercent: false },
    [Attribute.ConstructDurationReducePct]: { AttrName: '建造时间减少百分比', isPercent: true },
    [Attribute.ProduceDuration]: { AttrName: '生产时间值', isPercent: true },
    [Attribute.ProduceDurationReduce]: { AttrName: '生产时间减少', isPercent: true },
    [Attribute.ProduceDurationReducePct]: { AttrName: '生产时间减少百分比', isPercent: true },
    [Attribute.None]: { AttrName: '占位', isPercent: false },
}

export const BattleAttributes: { [AttributeId: number]: { AttrName: string, isPercent: boolean } } = {
    [BattleAttribute.None]: { AttrName: '占位', isPercent: false },
    [BattleAttribute.HPMax]: { AttrName: '最大生命力', isPercent: false },
    [BattleAttribute.HPMaxPct]: { AttrName: '生命力百分比', isPercent: true },
    [BattleAttribute.HPCur]: { AttrName: '当前生命力', isPercent: false },
    [BattleAttribute.AttackVal]: { AttrName: '攻击力', isPercent: false },
    [BattleAttribute.AttackPct]: { AttrName: '攻击力百分比', isPercent: true },
    [BattleAttribute.AttackSpeed]: { AttrName: '攻速', isPercent: false },
    [BattleAttribute.AttackSpeedPct]: { AttrName: '攻速提升百分比', isPercent: true },
    [BattleAttribute.StaminaPct]: { AttrName: '生命每秒恢复', isPercent: false },
    [BattleAttribute.GroundMoveSpeed]: { AttrName: '移动速度', isPercent: false },
    [BattleAttribute.GroundMoveSpeedPct]: { AttrName: '移动速度百分比', isPercent: true },
    [BattleAttribute.SkillCD]: { AttrName: '技能冷却', isPercent: false },
    [BattleAttribute.SkillCDPct]: { AttrName: '技能冷却缩减', isPercent: true },
    [BattleAttribute.CriticalPct]: { AttrName: '暴击率', isPercent: true },
    [BattleAttribute.CriticalIncrPct]: { AttrName: '暴击率百分比', isPercent: true },
    [BattleAttribute.CriticalDmgPct]: { AttrName: '暴击伤害', isPercent: true },
    [BattleAttribute.EvadeProb]: { AttrName: '闪避率', isPercent: true },
    [BattleAttribute.ShieldCoverMax]: { AttrName: '护盾最大值', isPercent: false },
    [BattleAttribute.ShieldCoverCur]: { AttrName: '护盾当前值', isPercent: false },
    [BattleAttribute.HitResumeVal]: { AttrName: '击中生命恢复', isPercent: false },
    [BattleAttribute.KillResumeVal]: { AttrName: '击杀生命恢复', isPercent: false },
    [BattleAttribute.DamageReduce]: { AttrName: '伤害减免', isPercent: true },
    [BattleAttribute.DamageIncrease]: { AttrName: '伤害增幅', isPercent: true },
    [BattleAttribute.Vampire]: { AttrName: '吸血', isPercent: true },
}

/**获取生产属性 */
export function getProductionAttributes(AttributeId: number) {
    return ProductionAttributes[AttributeId];
}

/**获取战斗属性 */
export function getBattleAttributes(AttributeId: number) {
    return BattleAttributes[AttributeId];
}

